version: '3'
services:

  webpack:
    image: 'node:9.9.0'
    command:
      - sh
      - '-c'
      - "yarn install --modules-folder ../node_modules && exec yarn start:dev"
    volumes:
      - "./frontend:/home/node/frontend"
    working_dir: /home/node/frontend
    environment:
      API_URL: http://api-dev:8080
    depends_on:
      - api-dev
    ports:
      - 8080:8080

  api-dev:
    volumes:
      - ".:/go/src/github.com/netice9/swarm-intelligence"
    build:
      context: 'docker-dev'
      dockerfile: 'Dockerfile-go'
    ports:
      - 9090:8080
    environment:
      DOCKER_HOST: tcp://swarm:2375
    depends_on:
      - swarm-init
      - swarm

  agent-dev:
    volumes:
      - ".:/go/src/github.com/netice9/swarm-intelligence"
    build:
      context: 'docker-dev'
      dockerfile: 'Dockerfile-go'
    environment:
      DOCKER_HOST: tcp://swarm:2375
    depends_on:
      - swarm-init
      - swarm
    command: ["reflex", "-R", "^frontend/", "-s", "--", "go", "run", "main.go", "agent", "--remote", "http://api-dev:9000"]


  swarm-init:
    image: 'docker:18.03.0-ce'
    command: ['sh', '-c', 'sleep 5 && docker swarm init']
    environment:
      DOCKER_HOST: tcp://swarm:2375
    depends_on:
      - swarm
  swarm:
    image: 'docker:18.03.0-ce-dind'
    privileged: true
